### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by nibra**
# Major Refactoring of the DI Container Tests

Some tests are removed completely without replacement, since they tested internal implementation details.
That kind of tests never tell us something useful, they just block refactoring of the tested class.
 
Tests using Reflection are either removed or refactored.
If you ever have to use Reflection in testing, you can bet, that the tested code is broken.

The fixture has been removed, since there was no setup.
It enhances the readability and safety of tests, if the test subject is instantiated in the test method.
Setting up fixtures in the `setUp()` method only makes sense, if
a) setup is more than just a `new ClassUnderTest`, and
b) that setup is used in several test methods.

Properties of stubs are made public, so they can be inspected without Reflection.

The test class was splitted up into several classes, each representing one feature.

The test results looked like this before

    Joomla\DI\Tests\ContainerAwareTrait
     [x] Get container exception
     [x] Get container
     [x] Set container
    
    Joomla\DI\Tests\Container
     [x] Constructor
     [x] Constructor with parent
     [x] Alias
     [x] Resolve alias set
     [x] Resolve alias not set
     [x] Resolve alias same as key
     [x] Build object no dependencies
     [x] Build object get dependency from container
     [x] Build object non class
     [x] Build shared object
     [x] Create child
     [x] Extend
     [x] Extend validates key is present
     [x] Exists resolves alias
     [x] Get method args from container
     [x] Get method args concrete class
     [x] Get method args default values
     [x] Get method args cant resolve
     [x] Get method args resolved is not instance of hinted dependency
     [x] Set callable
     [x] Set not callable
     [x] Set already set protected
     [x] Set already set not protected
     [x] Set shared
     [x] Set not shared
     [x] Protect
     [x] Protect shared
     [x] Share
     [x] Share protected
     [x] Get shared
     [x] Get not shared
     [x] Get not exists
     [x] Get passes container instance shared
     [x] Get passes container instance not shared
     [x] Exists
     [x] Get raw
     [x] Get raw from parent
     [x] Get new instance
     [x] Register service provider

And this is, how they look now:

    Joomla\DI\Tests\Aliasing
     [x] Both the original key and the alias return the same resource
     [x] exists() also resolves the alias if set.
     [ ] Child container resolves parent's alias to parent's resource
    
    Joomla\DI\Tests\ContainerAccess
     [x] The same resource instance is returned for shared resources
     [x] A new resource instance is returned for non-shared resources
     [x] Accessing an undefined resource throws an InvalidArgumentException
     [x] The existence of a resource can be checked
     [x] getNewInstance() will always return a new instance, even if the resource was set to be shared
    
    Joomla\DI\Tests\ContainerAwareTrait
     [x] Container can be set with setContainer() and retrieved with getContainer()
     [x] getContainer() throws an UnexpectedValueException, if no container is set
    
    Joomla\DI\Tests\ContainerSetup
     [x] Resources can be set up with Callables
     [x] Resources can be set up with Closures
     [x] Resources can be scalar values
     [x] Setting an existing protected resource throws an OutOfBoundsException
     [x] Setting an existing non-protected resource replaces the resource
     [x] Default mode is 'not shared' and 'not protected'
     [x] 'shared' and 'protected' mode can be set independently
     [x] The convenience method protect() sets resources as protected, but not as shared by default
     [x] The convenience method protect() sets resources as shared when passed true as third arg
     [x] The convenience method share() sets resources as shared, but not as protected by default
     [x] The convenience method share() sets resources as protected when passed true as third arg
     [x] The callback gets the container instance as a parameter
    
    Joomla\DI\Tests\DelegateLookup
     [x] Child container has access to parent's resources
     [x] When registering a service provider, its register() method is called with the container instance
    
    Joomla\DI\Tests\ObjectBuilding
     [x] Building an object returns an instance of the requested class
     [x] Building a non-shared object returns a new object whenever requested
     [x] Building a shared object returns the same object whenever requested
     [x] Attempting to build a non-class returns false
     [x] Dependencies are resolved from the container's known resources
     [x] Resources are created, if they are not present in the container
     [x] Dependencies are resolved from their default values
     [x] A DependencyResolutionException is thrown, if an object can not be built due to unspecified constructor parameter types
     [ ] A DependencyResolutionException is thrown, if an object can not be built due to dependency on unknown interfaces
    
    Joomla\DI\Tests\ResourceDecoration
     [x] An extended resource replaces the original resource
     [x] Attempting to extend an undefined resource throws an InvalidArgumentException

### CODE REVIEW

**Comment by mbabker** [comment]
Were you aiming to send this to the `master` branch or the `2.0-dev` branch?

**Comment by nibra** [comment]
Should be 2.0-dev

**Comment by mbabker** [comment]
Can you resubmit this?  It got opened against master.

**Comment by nibra** [comment]
Resubmitted to `2.0-dev` branch.

**Pull request closed without merging**
